--------------------------------------------------------
--  DDL for Table EMOJI
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."EMOJI" 
   (	"PARENT_NUM" NUMBER, 
	"CHILD_NUM" NUMBER, 
	"EMOJI_TYPE" NUMBER, 
	"MONEY_DATE" DATE, 
	"WRITE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMOJI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."EMOJI_PK" ON "KIDSBANK"."EMOJI" ("PARENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMOJI
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."EMOJI" ADD CONSTRAINT "EMOJI_PK" PRIMARY KEY ("PARENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("MONEY_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("PARENT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMOJI
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."EMOJI" ADD CONSTRAINT "FK_EMOJI_CHILD_NUM" FOREIGN KEY ("CHILD_NUM")
	  REFERENCES "KIDSBANK"."CHILD" ("CHILD_NUM") ENABLE;
