--------------------------------------------------------
--  DDL for Table MONEY_BOOK
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."MONEY_BOOK" 
   (	"MONEY_BOOK_NUM" NUMBER, 
	"CHILD_NUM" NUMBER, 
	"MONEY_TYPE" NUMBER, 
	"EXPORT_TYPE" VARCHAR2(30 BYTE), 
	"AMOUNT" NUMBER, 
	"CONTENT" VARCHAR2(100 BYTE), 
	"MEMO" VARCHAR2(200 BYTE), 
	"MONEY_DATE" DATE, 
	"WRITE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MONEY_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."MONEY_BOOK_PK" ON "KIDSBANK"."MONEY_BOOK" ("MONEY_BOOK_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MONEY_BOOK
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."MONEY_BOOK" ADD CONSTRAINT "MONEY_BOOK_PK" PRIMARY KEY ("MONEY_BOOK_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("MONEY_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("EXPORT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("MONEY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("MONEY_BOOK_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MONEY_BOOK
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."MONEY_BOOK" ADD CONSTRAINT "FK_MONEY_BOOK_CHILD_NUM" FOREIGN KEY ("CHILD_NUM")
	  REFERENCES "KIDSBANK"."CHILD" ("CHILD_NUM") ENABLE;
