--------------------------------------------------------
--  DDL for Table PARENT_CHILD
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."PARENT_CHILD" 
   (	"PARENT_CHILD_NUM" NUMBER, 
	"CHILD_NUM" NUMBER, 
	"PARENT_NUM" NUMBER, 
	"CHILD_ORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARENT_CHILD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."PARENT_CHILD_PK" ON "KIDSBANK"."PARENT_CHILD" ("PARENT_CHILD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PARENT_CHILD
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."PARENT_CHILD" ADD CONSTRAINT "PARENT_CHILD_PK" PRIMARY KEY ("PARENT_CHILD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("CHILD_ORDER" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("PARENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("PARENT_CHILD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PARENT_CHILD
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."PARENT_CHILD" ADD CONSTRAINT "FK_CHILD_NUM" FOREIGN KEY ("CHILD_NUM")
	  REFERENCES "KIDSBANK"."CHILD" ("CHILD_NUM") ENABLE;
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" ADD CONSTRAINT "FK_PARENT_NUM" FOREIGN KEY ("PARENT_NUM")
	  REFERENCES "KIDSBANK"."PARENT" ("PARENT_NUM") ENABLE;
